/*
    Operadores Matemáticos
    + Adição
    - Subtração
    / Divisão
    * Multiplicação
    % Módulo (resto da divisão e não o resultado)
    ** Exponenciação (Elevado à)

    Operadores Relacionais
    == Igual à
    != Desigual à
    >  Maior que
    <  Menor que
    >= Maior ou igual que
    <= Menor ou igual que
    


    A lista com todos operadores pode ser encontrada no link:
    https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators
*/

//Este exercicio não teve lá muita interação, foi mais informação mesmo.